import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"; // Imported Toaster from sonner as toast component is deprecated


import { Navbar } from "@/components/Nabar";
import { Footer } from "@/components/Footer";


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sans',
});

// Monospace font (replacing Geist Mono)
const robotoMono = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${inter.variable} ${robotoMono.variable}`}>
      <Navbar/>
        {children}

        <Toaster position="top-center" />
        <Footer/>
      </body>
      
    </html>
  );
}
